'use client';
import {adminText} from '@/lib/admin/translate';

import {useMemo,useRef,useState,useEffect} from 'react';
import {createPortal} from 'react-dom';
import Link from 'next/link';
import {Plus,ArrowUpRight,X,FileText,Printer,ChevronLeft,ChevronRight} from 'lucide-react';
import {MODULES,permission,actionsFor,actionPermission} from '@/lib/erp/config';
import {money,documentTotals} from '@/lib/erp/money';
import {officeToday} from '@/lib/ops/presentation';
import TableDataBar, {uniqueFilterOptions} from '@/components/admin/ui/TableDataBar';
import {downloadExcel} from '@/lib/admin/table-io';
import {payrollWpsRowsFromDocument} from '@/lib/erp/wps-export';
import {formatAdminDateTime} from '@/lib/admin/locale';

const LABELS={submit:'Submit for review',approve:'Approve',reject:'Return for changes',receive:'Confirm full receipt',post:'Post to ledger',reverse:'Reverse posting',contract:'Create contract',invoice:'Create invoice',bill:'Create supplier bill',payment:'Record payment',depreciate:'Post monthly depreciation',match:'Match statement',unmatch:'Unmatch',archive:'Archive',cancel:'Cancel document'};
function blank(module,taxRate){const config=MODULES[module];return {requestId:crypto.randomUUID(),date:officeToday(),period:officeToday().slice(0,7),probability:50,stage:'qualified',direction:'payment',bankAccount:'1000',...Object.fromEntries(config.fields.filter(f=>f.type==='checkbox').map(f=>[f.key,false])),...(config.lines?{lines:[{description:'',quantity:1,unitPrice:'',taxRate}]}:{}),...(config.journal?{lines:[{account:'1000',debit:'',credit:''},{account:'3000',debit:'',credit:''}]}:{}),...(config.payroll?{employees:[{employeeId:'',base:'',allowance:0,deduction:0}]}:{})};}
function can(actor,required){return actor.role==='super_admin'||actor.permissions.includes(required);}
export function ErpMetrics({items}){return <div className="erp-metrics">{items.map(item=><div key={item.label} className={`erp-metric ${item.tone||''}`}><span>{adminText(item.label)}</span><strong>{adminText(item.value)}</strong><small>{adminText(item.hint)}</small></div>)}</div>;}
export function ErpEmpty({title='No records yet',description='Create your first record to start this workflow.'}){return <div className="erp-empty"><FileText size={30}/><h3>{adminText(title)}</h3><p>{adminText(description)}</p></div>;}
export function ErpModal({title,children,onClose,busy=false,wide=false}){
  const ref=useRef(null);
  const closeRef=useRef(onClose);
  useEffect(()=>{closeRef.current=onClose;},[onClose]);
  useEffect(()=>{const previous=document.activeElement;const node=ref.current;node?.focus();function key(event){if(event.key==='Escape'&&!busy)closeRef.current();if(event.key==='Tab'){const elements=Array.from(node.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]'));if(!elements.length){event.preventDefault();return;}const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===node)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}node?.addEventListener('keydown',key);return()=>{node?.removeEventListener('keydown',key);previous?.focus?.();};},[busy]);
  const [mounted,setMounted]=useState(false);
  useEffect(()=>setMounted(true),[]);
  const ui=<div className="erp-modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section ref={ref} tabIndex={-1} className={`erp-modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={adminText(title)} onMouseDown={(event)=>event.stopPropagation()}><header><div><span className="erp-eyebrow">{adminText("ASAS / Business workspace")}</span><h2>{adminText(title)}</h2></div><button className="erp-icon-btn" type="button" aria-label={adminText("Close dialog")} onClick={onClose} disabled={busy}><X size={20}/></button></header>{children}</section></div>;
  if(!mounted) return null;
  const host=document.querySelector('.admin-ar[data-theme], .admin-en[data-theme]')||document.body;
  return createPortal(ui, host);
}
export default function ErpRegister({module,initialData,actor,selectedId=''}){
  const config=MODULES[module];const [data,setData]=useState(initialData);const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);
  const [editor,setEditor]=useState(null);const [detail,setDetail]=useState(initialData.items.find(r=>r.id===selectedId)||null);const [action,setAction]=useState(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const filtered=useMemo(()=>data.items.filter(r=>(!status||r.status===status)&&[r.number,r.title,r.name,r.reference,r.notes].join(' ').toLowerCase().includes(query.toLowerCase())),[data.items,query,status]);
  const lastPage=Math.max(1,Math.ceil(filtered.length/15));const currentPage=Math.min(page,lastPage);
  const lookups=data.lookups;const label=(source,id)=>lookups[source]?.find(o=>o.id===id)?.label||id||'—';
  async function request(body){const res=await fetch('/api/admin/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(result.error||'Operation failed');return result;}
  async function refresh(){const res=await fetch(`/api/admin/erp?module=${module}`,{cache:'no-store'});const result=await res.json();if(!res.ok)throw new Error(result.error||'Could not refresh');setData(result);return result;}
  function edit(record){setError('');setEditor({module,lookups,draft:record?{...record,...(config.journal?{lines:record.lines.map(l=>({...l,debit:l.debit/100,credit:l.credit/100}))}:{})}:blank(module,data.defaultTaxRate)});setDetail(null);}
  async function startAction(record,key){
    setError('');
    if(key==='payment'){
      setBusy(true);try{const res=await fetch('/api/admin/erp?module=payments');const result=await res.json();if(!res.ok)throw new Error(result.error);setEditor({module:'payments',lookups:result.lookups,draft:{...blank('payments',0),title:`Settlement of ${record.number}`,target:record.id,amount:record.outstandingMinor/100}});setDetail(null);}catch(err){setError(err.message);}finally{setBusy(false);}return;
    }
    setAction({record,key,date:officeToday(),reason:''});
  }
  async function save(event){event.preventDefault();setBusy(true);setError('');try{const saved=await request({module:editor.module,document:editor.draft});await refresh();setEditor(null);setNotice(editor.module==='payments'?<>{adminText("Payment draft saved. ")}<Link href={`/admin/erp/payments?record=${saved.document.id}`}>{adminText("Open payment")}</Link>{adminText(" to review and post it.")}</>:'Record saved.');}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function execute(event){event.preventDefault();setBusy(true);setError('');try{const result=await request({module,id:action.record.id,action:action.key,document:{version:action.record.version,date:action.date,reason:action.reason}});await refresh();setDetail(result.document);setNotice(`${LABELS[action.key]} completed.`);setAction(null);}catch(err){setError(err.message);}finally{setBusy(false);}}
  const active=data.items.filter(r=>!['cancelled','reversed','archived','rejected'].includes(r.status));
  const stats=[{label:'Records',value:data.items.length,hint:config.label},{label:'Awaiting review',value:data.items.filter(r=>r.status==='submitted').length,hint:'Submitted for approval',tone:'amber'},{label:'Posted / approved',value:data.items.filter(r=>['posted','approved','matched'].includes(r.status)).length,hint:'Completed control step',tone:'green'}];
  if(!config.master)stats.push({label:['invoices','bills'].includes(module)?'Outstanding':'Active record value',value:money(active.reduce((n,r)=>n+(['invoices','bills'].includes(module)?r.outstandingMinor||0:r.totalMinor||0),0),data.currency),hint:['invoices','bills'].includes(module)?'Posted documents, less settlements':'Sum across active records'});
  const editorConfig=editor?MODULES[editor.module]:null;
  const setField=(key,value)=>setEditor(e=>({...e,draft:{...e.draft,[key]:value}}));
  const updateRow=(collection,index,key,value)=>setEditor(e=>({...e,draft:{...e.draft,[collection]:e.draft[collection].map((r,i)=>i===index?{...r,[key]:value}:r)}}));
  let totals=null;if(editorConfig?.lines){try{totals=documentTotals(editor.draft.lines);}catch{ /* Incomplete input remains editable. */ }}
  const recordActions=(record)=>actionsFor(module,record).filter(key=>can(actor,actionPermission(module,key)));
  const tableColumns=[{key:'number',label:'Reference'},{key:'title',label:'Description'},{key:'name',label:'Name'},{key:'date',label:'Date'},{key:'status',label:'Status'},...config.fields.map(f=>({key:f.key,label:f.label})),...(!config.master?[{key:'amountDisplay',label:`Amount (${data.currency})`}]:[])];
  const tableRows=filtered.map(r=>({...r,amountDisplay:((r.totalMinor||0)/100).toFixed(2)}));
  async function importExcel(mapped){
    setBusy(true);setError('');
    try{
      for(const row of mapped){
        const draft={...blank(module,data.defaultTaxRate),...row,requestId:crypto.randomUUID()};
        delete draft.id;delete draft.version;delete draft.number;delete draft.status;delete draft.amountDisplay;
        await request({module,document:draft});
      }
      await refresh();setNotice(adminText('Import completed.'));
    }catch(err){setError(err.message);}finally{setBusy(false);}
  }
  return <div className="erp-stack">
    <ErpMetrics items={stats}/>
    {error && !editor && !action ? <div role="alert" className="erp-error">{adminText(error)}</div> : null}
    {notice ? <div role="status" className="erp-notice">{typeof notice === 'string' ? adminText(notice) : notice}</div> : null}
    <div className="erp-register"><div className="erp-toolbar"><TableDataBar query={query} onQuery={(value)=>{setQuery(value);setPage(1);}} searchPlaceholder="Search reference, description or notes…" filter={status} onFilter={(value)=>{setStatus(value);setPage(1);}} filterLabel="All statuses" filterOptions={uniqueFilterOptions(data.items,'status')} columns={tableColumns} rows={tableRows} filename={module} title={config.label} canImport={can(actor,permission(config.domain,'write'))} onImport={importExcel} extra={can(actor,permission(config.domain,'write'))?<button className="erp-btn" onClick={()=>edit(null)}><Plus size={16}/>{adminText(`New ${config.singular.toLowerCase()}`)}</button>:null}/></div>
      <div className="erp-table-scroll"><table className="erp-table"><thead><tr><th>{adminText("Reference / description")}</th><th>{adminText(config.master?'Contact':'Document date')}</th><th>{adminText("Related record")}</th><th>{adminText("Status")}</th>{!config.master&&<th className="numeric">{adminText("Amount")}</th>}<th/></tr></thead><tbody>{filtered.slice((currentPage-1)*15,currentPage*15).map(record=><tr key={record.id}><td><button className="erp-record-link" onClick={()=>setDetail(record)}>{record.number}</button><small>{record.title||record.name}</small></td><td>{config.master?record.email||record.phone||'—':record.date||record.expectedDate||'—'}{record.dueDate&&<small>{adminText("Due ")}{adminText(record.dueDate)}</small>}</td><td>{adminText(record.projectId?label('projects',record.projectId):record.clientId?label('clients',record.clientId):record.vendorId?label('vendors',record.vendorId):record.employeeId?label('employees',record.employeeId):record.sourceNumber||'—')}</td><td><span className={`erp-status ${record.status}`}>{adminText(record.status)}</span></td>{!config.master&&<td className="numeric">{adminText(money(record.totalMinor,data.currency))}{record.outstandingMinor>0&&<small>{adminText("Open ")}{adminText(money(record.outstandingMinor,data.currency))}</small>}</td>}<td><button className="erp-icon-btn" aria-label={adminText(`Open ${record.number}`)} onClick={()=>setDetail(record)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table></div>
      {!filtered.length&&<ErpEmpty title={adminText(data.items.length?'No matching records':`No ${config.label.toLowerCase()} yet`)} description={adminText(data.items.length?'Adjust your search or status filter.':config.description)}/>}
      <footer className="erp-pagination"><span>{adminText(filtered.length)}{adminText(" records · ")}{adminText(data.currency)}</span><div><button aria-label={adminText("Previous page")} disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><span>{adminText(currentPage)} / {adminText(lastPage)}</span><button aria-label={adminText("Next page")} disabled={currentPage>=lastPage} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div></footer>
    </div>
    {detail&&!editor&&!action&&<ErpModal title={adminText(detail.number)} onClose={()=>setDetail(null)} wide><div className="erp-modal-body erp-print"><div className="erp-document-head"><div><span className="erp-eyebrow">{adminText(detail.companySnapshot?.companyName||'ASAS Engineering')}</span><h2>{detail.title||detail.name}</h2><p>{adminText(detail.companySnapshot?.address)}</p>{detail.companySnapshot?.taxNumber&&<p>{adminText("Tax registration: ")}{adminText(detail.companySnapshot.taxNumber)}</p>}</div><span className={`erp-status ${detail.status}`}>{adminText(detail.status)}</span></div>{detail.partySnapshot&&<div className="erp-callout"><strong>{detail.partySnapshot.name}</strong><p>{detail.partySnapshot.address}</p></div>}<dl className="erp-details">{config.fields.map(f=><div key={f.key}><dt>{adminText(f.label)}</dt><dd>{adminText(f.type==='reference'?(f.key==='target'&&detail.targetNumber?detail.targetNumber:label(f.source,detail[f.key])):f.type==='checkbox'?(detail[f.key]?'Yes':'No'):String(detail[f.key]||'—'))}</dd></div>)}</dl>
      {config.lines&&<div className="erp-table-scroll"><table className="erp-table"><thead><tr><th>{adminText("Description")}</th><th>{adminText("Qty")}</th><th>{adminText("Unit price")}</th><th>{adminText("Tax %")}</th><th>{adminText("Total")}</th></tr></thead><tbody>{detail.lines.map((l,i)=><tr key={i}><td>{adminText(l.description)}</td><td>{adminText(l.quantity)}</td><td>{adminText(money(Math.round(l.unitPrice*100),data.currency))}</td><td>{adminText(l.taxRate)}%</td><td>{adminText(money(l.totalMinor,data.currency))}</td></tr>)}</tbody></table></div>}
      {config.journal&&<div className="erp-table-scroll"><table className="erp-table"><thead><tr><th>{adminText("Account")}</th><th>{adminText("Debit")}</th><th>{adminText("Credit")}</th></tr></thead><tbody>{detail.lines.map((l,i)=><tr key={i}><td>{adminText(l.account)}</td><td>{adminText(money(l.debit,data.currency))}</td><td>{adminText(money(l.credit,data.currency))}</td></tr>)}</tbody></table></div>}
      {config.payroll&&<div className="erp-table-scroll"><table className="erp-table"><thead><tr><th>{adminText("Employee")}</th><th>{adminText("Base")}</th><th>{adminText("Allowances")}</th><th>{adminText("Withholdings")}</th><th>{adminText("Net pay")}</th></tr></thead><tbody>{detail.employees.map(l=><tr key={l.employeeId}><td>{l.name}</td><td>{adminText(money(l.baseMinor,data.currency))}</td><td>{adminText(money(l.allowanceMinor,data.currency))}</td><td>{adminText(money(l.deductionMinor,data.currency))}</td><td>{adminText(money(l.netMinor,data.currency))}</td></tr>)}</tbody></table></div>}
      {detail.totalMinor!=null&&<div className="erp-totals">{detail.subtotalMinor!=null&&<span>{adminText("Subtotal ")}<b>{adminText(money(detail.subtotalMinor,data.currency))}</b></span>}{detail.taxMinor!=null&&<span>{adminText("Tax ")}<b>{adminText(money(detail.taxMinor,data.currency))}</b></span>}<strong>{adminText("Total ")}<b>{adminText(money(detail.totalMinor,data.currency))}</b></strong>{detail.status==='posted'&&['invoices','bills','expenses','assets','payroll'].includes(module)&&<span>{adminText("Outstanding ")}<b>{adminText(money(detail.outstandingMinor,data.currency))}</b></span>}{module==='assets'&&<span>{adminText("Net book value ")}<b>{adminText(money(detail.totalMinor-(detail.depreciatedMinor||0),data.currency))}</b></span>}</div>}
      {detail.convertedId&&<div className="erp-callout">{adminText("Created ")}<Link href={`/admin/erp/${detail.convertedModule}?record=${detail.convertedId}`}>{adminText(detail.convertedNumber)}</Link></div>}{detail.reversalReason&&<div className="erp-callout">{adminText("Reversal reason: ")}{adminText(detail.reversalReason)}</div>}{detail.reason&&<div className="erp-callout">{adminText("Review: ")}{adminText(detail.reason)}</div>}
      <div className="erp-record-meta">{adminText("Created ")}{formatAdminDateTime(detail.createdAt)}{adminText(" · Revision ")}{adminText(detail.version)}{detail.postedAt?`${adminText(' · Posted ')}${formatAdminDateTime(detail.postedAt)}`:''}</div>
      </div><footer className="erp-modal-footer"><button className="erp-btn secondary" onClick={()=>window.print()}><Printer size={15}/>{adminText("Print")}</button>{module==='payroll'&&<button type="button" className="erp-btn secondary" onClick={()=>downloadExcel(`wps-${detail.number}`,[{key:'employeeId',label:'EmployeeUID'},{key:'name',label:'EmployeeName'},{key:'routingCode',label:'RoutingCode'},{key:'startDate',label:'PayStart'},{key:'endDate',label:'PayEnd'},{key:'income',label:'FixedIncome'},{key:'hours',label:'DaysInPeriod'}],payrollWpsRowsFromDocument(detail))}>{adminText("WPS Excel")}</button>}{['draft','active','rejected'].includes(detail.status)&&can(actor,permission(config.domain,'write'))&&<button className="erp-btn secondary" onClick={()=>edit(detail)}>{adminText("Edit")}</button>}{recordActions(detail).map(key=><button disabled={busy} key={key} className={`erp-btn ${['cancel','reverse','reject','archive','unmatch'].includes(key)?'secondary':''}`} onClick={()=>startAction(detail,key)}>{adminText(LABELS[key])}</button>)}</footer></ErpModal>}
    {editor&&<ErpModal title={adminText(`${editor.draft.id?'Edit':'New'} ${editorConfig.singular.toLowerCase()}`)} onClose={()=>setEditor(null)} busy={busy} wide={Boolean(editorConfig.lines||editorConfig.journal||editorConfig.payroll)}><form onSubmit={save}><div className="erp-modal-body">{error&&<div className="erp-error" role="alert">{adminText(error)}</div>}<fieldset disabled={busy}><div className="erp-form-grid">{editorConfig.fields.map(field=><label key={field.key} className={`erp-field ${field.type==='textarea'?'full':''}`}><span>{adminText(field.label)}{adminText(field.required?' *':'')}</span>{field.type==='reference'?<select required={field.required} value={editor.draft[field.key]||''} onChange={e=>setField(field.key,e.target.value)}><option value="">{adminText("Select…")}</option>{editor.lookups[field.source]?.map(o=><option key={o.id} value={o.id}>{adminText(o.label)}</option>)}</select>:field.type==='select'?<select required={field.required} value={editor.draft[field.key]||field.options[0]} onChange={e=>setField(field.key,e.target.value)}>{field.options.map(o=><option key={o} value={o}>{adminText(o)}</option>)}</select>:field.type==='textarea'?<textarea rows={3} value={editor.draft[field.key]||''} onChange={e=>setField(field.key,e.target.value)}/>:field.type==='checkbox'?<input type="checkbox" checked={Boolean(editor.draft[field.key])} onChange={e=>setField(field.key,e.target.checked)}/>:<input required={field.required} type={field.type==='money'?'number':field.type} min={['money','number'].includes(field.type)?0:undefined} step={field.type==='money'?'0.01':field.type==='number'?'0.001':undefined} value={editor.draft[field.key]??''} onChange={e=>setField(field.key,e.target.value)}/>}</label>)}</div>
      {(editorConfig.lines||editorConfig.journal)&&<div className="erp-lines"><div className="erp-section-heading"><h3>{adminText(editorConfig.journal?'Journal lines':'Line items')}</h3><button type="button" className="erp-btn secondary" onClick={()=>setField('lines',[...editor.draft.lines,editorConfig.journal?{account:'',debit:'',credit:''}:{description:'',quantity:1,unitPrice:'',taxRate:data.defaultTaxRate}])}><Plus size={14}/>{adminText("Add line")}</button></div>{editor.draft.lines.map((line,index)=><div className={`erp-line ${editorConfig.journal?'journal':''}`} key={index}>{editorConfig.journal?<><label className="erp-field"><span>{adminText("Account")}</span><select required value={line.account} onChange={e=>updateRow('lines',index,'account',e.target.value)}><option value="">{adminText("Select account")}</option>{editor.lookups.accounts?.map(a=><option key={a.id} value={a.id}>{adminText(a.label)}</option>)}</select></label>{['debit','credit'].map(key=><label key={key} className="erp-field"><span>{adminText(key)}</span><input aria-label={adminText(`${key} line ${index+1}`)} type="number" min="0" step="0.01" value={line[key]} onChange={e=>updateRow('lines',index,key,e.target.value)}/></label>)}</>:<><label className="erp-field"><span>{adminText("Description")}</span><input aria-label={adminText(`Description line ${index+1}`)} required value={line.description} onChange={e=>updateRow('lines',index,'description',e.target.value)}/></label>{[['quantity','Quantity','0.001'],['unitPrice','Unit price','0.01'],['taxRate','Tax %','0.01']].map(([key,label,step])=><label key={key} className="erp-field"><span>{adminText(label)}</span><input aria-label={adminText(`${label} line ${index+1}`)} required type="number" min={key==='quantity'?'0.001':'0'} max={key==='taxRate'?100:undefined} step={step} value={line[key]} onChange={e=>updateRow('lines',index,key,e.target.value)}/></label>)}</>}<button type="button" className="erp-icon-btn" aria-label={adminText(`Remove line ${index+1}`)} disabled={editor.draft.lines.length<=(editorConfig.journal?2:1)} onClick={()=>setField('lines',editor.draft.lines.filter((_,i)=>i!==index))}><X size={16}/></button></div>)}{totals&&<div className="erp-totals"><span>{adminText("Subtotal ")}<b>{adminText(money(totals.subtotalMinor,data.currency))}</b></span><span>{adminText("Tax ")}<b>{adminText(money(totals.taxMinor,data.currency))}</b></span><strong>{adminText("Total ")}<b>{adminText(money(totals.totalMinor,data.currency))}</b></strong></div>}</div>}
      {editorConfig.payroll&&<div className="erp-lines"><div className="erp-section-heading"><h3>{adminText("Employee pay components")}</h3><button type="button" className="erp-btn secondary" onClick={()=>setField('employees',[...editor.draft.employees,{employeeId:'',base:'',allowance:0,deduction:0}])}>{adminText("Add employee")}</button></div><p className="erp-muted">{adminText("Enter approved salary amounts. Statutory deductions and payment files are not calculated automatically.")}</p>{editor.draft.employees.map((row,index)=><div className="erp-line" key={index}><label className="erp-field"><span>{adminText("Employee")}</span><select required value={row.employeeId} onChange={e=>updateRow('employees',index,'employeeId',e.target.value)}><option value="">{adminText("Select employee")}</option>{editor.lookups.employees?.map(e=><option key={e.id} value={e.id}>{adminText(e.label)}</option>)}</select></label>{[['base','Base pay'],['allowance','Allowances'],['deduction','Withholdings']].map(([key,label])=><label key={key} className="erp-field"><span>{adminText(label)}</span><input required type="number" min="0" step="0.01" value={row[key]} onChange={e=>updateRow('employees',index,key,e.target.value)}/></label>)}<button type="button" className="erp-icon-btn" aria-label={adminText(`Remove employee ${index+1}`)} disabled={editor.draft.employees.length===1} onClick={()=>setField('employees',editor.draft.employees.filter((_,i)=>i!==index))}><X size={16}/></button></div>)}</div>}
      </fieldset></div><footer className="erp-modal-footer"><button type="button" className="erp-btn secondary" disabled={busy} onClick={()=>setEditor(null)}>{adminText("Cancel")}</button><button className="erp-btn" disabled={busy}>{adminText(busy?'Saving…':'Save draft')}</button></footer></form></ErpModal>}
    {action&&<ErpModal title={adminText(LABELS[action.key])} onClose={()=>setAction(null)} busy={busy}><form onSubmit={execute}><div className="erp-modal-body">{error&&<div className="erp-error" role="alert">{adminText(error)}</div>}<p>{action.record.number} · {action.record.title||action.record.name}</p><p className="erp-muted">{adminText(action.key==='post'?'Posting creates a balanced accounting entry. Posted documents are corrected with a reversal.':action.key==='receive'?'Confirm that all goods or services on this purchase order have been received.':action.key==='depreciate'?'Record one month of straight-line depreciation for this asset.':`Confirm ${LABELS[action.key].toLowerCase()} for this record.`)}</p>{['reverse','depreciate'].includes(action.key)&&<label className="erp-field"><span>{adminText("Accounting date")}</span><input required type="date" value={action.date} onChange={e=>setAction({...action,date:e.target.value})}/></label>}{['reverse','reject'].includes(action.key)&&<label className="erp-field"><span>{adminText("Reason")}</span><textarea required value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})}/></label>}</div><footer className="erp-modal-footer"><button type="button" className="erp-btn secondary" disabled={busy} onClick={()=>setAction(null)}>{adminText("Back")}</button><button className="erp-btn" disabled={busy}>{adminText(busy?'Processing…':LABELS[action.key])}</button></footer></form></ErpModal>}
  </div>;
}
