'use client';
import {adminText} from '@/lib/admin/translate';

import {useMemo,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {money} from '@/lib/erp/money';
import {ErpMetrics,ErpEmpty} from './ErpRegister';
import TableDataBar from '@/components/admin/ui/TableDataBar';
const VIEWS=[['trial','Trial balance'],['profit','Profit & loss'],['balance','Balance sheet'],['aging','Receivables & payables'],['ledger','General ledger'],['projects','Project costs'],['vat','VAT position']];
export default function ErpReports({initialReport}){
  const [report,setReport]=useState(initialReport);const [view,setView]=useState('trial');const [from,setFrom]=useState(initialReport.from);const [to,setTo]=useState(initialReport.to);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [query,setQuery]=useState('');
  async function refresh(e){e.preventDefault();setBusy(true);setError('');try{const res=await fetch(`/api/admin/erp?module=reports&from=${from}&to=${to}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error);setReport(data);}catch(err){setError(err.message);}finally{setBusy(false);}}
  const fmt=n=>money(n,report.currency);let columns=[],rows=[];
  if(view==='trial'){columns=[['code','Account'],['name','Description'],['debit','Debits'],['credit','Credits'],['balance','Net debit / credit']];rows=report.trial.map(r=>({...r,debit:fmt(r.debit),credit:fmt(r.credit),balance:fmt(r.balance)}));}
  if(view==='profit'){columns=[['code','Account'],['name','Description'],['type','Type'],['amount','Amount']];rows=report.period.map(r=>({...r,amount:fmt(r.type==='income'?r.credit-r.debit:r.debit-r.credit)}));}
  if(view==='balance'){columns=[['name','Category'],['amount','Amount']];rows=[['Assets',report.balanceSheet.assets],['Liabilities',report.balanceSheet.liabilities],['Equity accounts',report.balanceSheet.equity],['Cumulative earnings',report.balanceSheet.retained],['Liabilities + equity + earnings',report.balanceSheet.liabilities+report.balanceSheet.equity+report.balanceSheet.retained]].map(([name,amount])=>({name,amount:fmt(amount)}));}
  if(view==='aging'){columns=[['number','Document'],['party','Counterparty'],['module','Type'],['dueDate','Due'],['bucket','Age'],['outstanding','Outstanding']];rows=report.aging.map(r=>({...r,outstanding:fmt(r.outstanding)}));}
  if(view==='ledger'){columns=[['date','Date'],['number','Source'],['memo','Description'],['account','Account'],['debit','Debit'],['credit','Credit']];rows=report.ledger.map(r=>({...r,debit:fmt(r.debit),credit:fmt(r.credit)}));}
  if(view==='projects'){columns=[['code','Code'],['name','Project'],['budget','Budget'],['ledgerCost','Posted costs'],['effortCost','Internal effort estimate'],['hours','Approved hours'],['variance','Budget remaining']];rows=report.projects.map(r=>({...r,budget:fmt(r.budget),ledgerCost:fmt(r.ledgerCost),effortCost:fmt(r.effortCost),variance:fmt(r.variance)}));}
  if(view==='vat'){const vat=report.vat||{};columns=[['label','Item'],['amount','Amount']];rows=[{label:'Input tax (recoverable)',amount:fmt(vat.inputTax||0)},{label:'Output tax (payable)',amount:fmt(vat.outputTax||0)},{label:'Net VAT payable / (refund)',amount:fmt(vat.netPayable||0)}];}
  const totalDebit=report.trial.reduce((s,r)=>s+r.debit,0),totalCredit=report.trial.reduce((s,r)=>s+r.credit,0);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(row=>Object.values(row).join(' ').toLowerCase().includes(q));},[rows,query]);
  return <div className="erp-stack"><ErpMetrics items={[{label:'Revenue in period',value:fmt(report.income),hint:`${report.from} → ${report.to}`},{label:'Expenses in period',value:fmt(report.expense),hint:'Posted expense accounts'},{label:'Net result',value:fmt(report.profit),hint:'Revenue less expenses',tone:report.profit>=0?'green':'amber'},{label:'Trial balance',value:totalDebit===totalCredit?'Balanced':'Out of balance',hint:`Debits ${fmt(totalDebit)} · Credits ${fmt(totalCredit)}`,tone:totalDebit===totalCredit?'green':'amber'}]}/>
    <div className="erp-register"><form className="erp-toolbar" onSubmit={refresh}><label className="erp-field"><span>{adminText("From")}</span><input required type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="erp-field"><span>{adminText("Through")}</span><input required type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="erp-btn" disabled={busy}><RefreshCw size={15}/>{adminText(busy?'Loading…':'Apply dates')}</button><TableDataBar query={query} onQuery={setQuery} columns={columns.map(([key,label])=>({key,label}))} rows={visible} filename={`${view}-${report.to}`} title={VIEWS.find(v=>v[0]===view)?.[1]||'Report'}/></form>{error&&<div role="alert" className="erp-error">{adminText(error)}</div>}<div className="erp-tabs">{VIEWS.map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{adminText(label)}</button>)}</div><div className="erp-report-note">{adminText(['trial','balance','aging','projects'].includes(view)?`Position as of ${report.to}. The start date applies only to profit & loss and general ledger.`:`Transactions from ${report.from} through ${report.to}.`)}{adminText(view==='projects'&&' Internal effort is a management estimate from approved timesheets; it is not an additional general-ledger payroll posting.')}{adminText(view==='ledger'&&' The display and export include the latest 2,000 lines for the selected period.')}</div><div className="erp-table-scroll"><table className="erp-table"><thead><tr>{columns.map(([key,label])=><th key={key}>{adminText(label)}</th>)}</tr></thead><tbody>{visible.map((row,index)=><tr key={index}>{columns.map(([key])=><td key={key}>{adminText(row[key])}</td>)}</tr>)}</tbody></table></div>{!visible.length&&<ErpEmpty title={adminText("No posted activity in this period")} description={adminText("Reports update from posted documents and approved project time.")}/>}</div></div>;
}
