'use client';
import {adminText} from '@/lib/admin/translate';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import AdminCloseButton from '@/components/admin/ui/AdminCloseButton';
import {OpsMetrics, OpsEmpty} from './OpsUI';

const newStage = () => ({id: crypto.randomUUID(), nameEn:'', nameAr:'', descriptionEn:'', responsibleDepartmentId:'', responsibleRole:'', requiresApproval:false, requiredDocuments:'', active:true});
export default function StageTemplatesManager({initialTemplates = [], departments = [], canWrite = false}) {
  const router = useRouter();
  const [templates,setTemplates] = useState(initialTemplates);
  const [draft,setDraft] = useState(null);
  const [saving,setSaving] = useState(false);
  const [error,setError] = useState('');
  const [query,setQuery] = useState('');
  function open(tpl, clone = false) {
    setError('');
    setDraft(tpl ? {...tpl, ...(clone ? {id:undefined,nameEn:`${tpl.nameEn} — copy`,isDefault:false} : {}),items:[...(tpl.items || [])].sort((a,b)=>a.order-b.order).map(item=>({...item,...(clone ? {id:crypto.randomUUID()} : {})}))} : {nameEn:'',nameAr:'',descriptionEn:'',isDefault:false,active:true,items:[newStage()]});
  }
  function editStage(id, patch) { setDraft(d=>({...d,items:d.items.map(i=>i.id===id ? {...i,...patch} : i)})); }
  function move(index, direction) { setDraft(d=>{const items=[...d.items];[items[index],items[index+direction]]=[items[index+direction],items[index]];return {...d,items};}); }
  async function save(e) {
    e.preventDefault(); if (!canWrite || saving) return; setSaving(true);setError('');
    try {
      const res=await fetch('/api/admin/ops',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'stage-templates',document:{...draft,items:draft.items.map((i,index)=>({...i,order:index+1}))}})});
      const data=await res.json();if(!res.ok)throw new Error(data.error || 'Could not save workflow');
      setTemplates(t=>[...t.filter(x=>x.id!==data.document.id).map(x=>data.document.isDefault?{...x,isDefault:false}:x),data.document]);setDraft(null);router.refresh();
    } catch(err){setError(err.message);} finally {setSaving(false);}
  }
  return <div className="adm-stack">
    <OpsMetrics items={[{label:'Workflow templates',value:templates.length,hint:'Reusable delivery plans'},{label:'Active templates',value:templates.filter(t=>t.active).length,hint:'Available for project setup',tone:'good'},{label:'Review gates',value:templates.reduce((n,t)=>n+t.items.filter(i=>i.requiresApproval).length,0),hint:'Stages marked for approval'}]}/>
    <div className="ops-toolbar"><input aria-label={adminText("Search workflows")} placeholder={adminText("Search workflow templates…")} value={query} onChange={e=>setQuery(e.target.value)}/>{canWrite&&<button className="adm-btn" onClick={()=>open(null)}>{adminText("+ New workflow")}</button>}</div>
    <div className="ops-project-cards">{templates.filter(t=>`${t.nameEn} ${t.descriptionEn}`.toLowerCase().includes(query.toLowerCase())).map(t=><article className="ops-project-card" key={t.id}><span className={`ops-pill ${t.isDefault?'good':''}`}>{adminText(t.isDefault?'Default workflow':t.active?'Active':'Inactive')}</span><h3>{t.nameEn}</h3><p>{t.descriptionEn || adminText('A structured delivery plan for your project team.')}</p><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:16}}>{t.items.slice(0,3).map(i=><span className="ops-pill" key={i.id}>{i.nameEn}</span>)}{t.items.length>3&&<span className="ops-pill">+{adminText(t.items.length-3)}{adminText(" stages")}</span>}</div><footer><span>{adminText(t.items.length)}{adminText(" stages · ")}{adminText(t.items.filter(i=>i.requiresApproval).length)}{adminText(" review gates")}</span></footer><div style={{marginTop:12}}><button className="adm-btn-ghost" onClick={()=>open(t)}>{adminText(canWrite?'Edit workflow':'View workflow')}</button>{canWrite&&<button className="adm-btn-ghost" onClick={()=>open(t,true)}>{adminText("Duplicate")}</button>}</div></article>)}</div>
    {!templates.length&&<OpsEmpty title={adminText("Create your first workflow")} description={adminText("Define delivery stages, responsibilities and required documents.")}/>}
    {draft&&<div className="adm-modal-backdrop" onClick={()=>!saving&&setDraft(null)}><div className="adm-modal" style={{maxWidth:900}} role="dialog" aria-modal="true" aria-label={adminText("Workflow editor")} onClick={e=>e.stopPropagation()}><div className="adm-modal-head"><h2>{adminText(draft.id?'Workflow editor':'New workflow')}</h2><AdminCloseButton disabled={saving} onClick={()=>setDraft(null)}/></div><form onSubmit={save}><div className="adm-modal-body">{error&&<p className="adm-error" role="alert">{adminText(error)}</p>}<fieldset disabled={!canWrite||saving} style={{border:0,padding:0,margin:0}}><div className="adm-grid-2"><label className="adm-field">{adminText("Name (EN)")}<input required value={draft.nameEn} onChange={e=>setDraft({...draft,nameEn:e.target.value})}/></label><label className="adm-field">{adminText("Name (AR)")}<input dir="rtl" value={draft.nameAr||''} onChange={e=>setDraft({...draft,nameAr:e.target.value})}/></label></div><label className="adm-field">{adminText("Description")}<textarea rows={2} value={draft.descriptionEn||''} onChange={e=>setDraft({...draft,descriptionEn:e.target.value})}/></label><div className="ops-toolbar" style={{marginBottom:22}}><label className="adm-check"><input type="checkbox" checked={draft.isDefault} onChange={e=>setDraft({...draft,isDefault:e.target.checked,active:e.target.checked?true:draft.active})}/>{adminText("Default for new projects")}</label><label className="adm-check"><input type="checkbox" disabled={draft.isDefault} checked={draft.active!==false} onChange={e=>setDraft({...draft,active:e.target.checked})}/>{adminText("Active")}</label></div>
    {draft.items.map((item,index)=><div className="ops-stage-editor" key={item.id}><div className="ops-stage-title"><span className="ops-avatar">{adminText(String(index+1).padStart(2,'0'))}</span><strong>{item.nameEn||adminText('New stage')}</strong><button type="button" aria-label={adminText(`Move stage ${index+1} up`)} disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button type="button" aria-label={adminText(`Move stage ${index+1} down`)} disabled={index===draft.items.length-1} onClick={()=>move(index,1)}>↓</button><button type="button" disabled={draft.items.length===1} onClick={()=>setDraft({...draft,items:draft.items.filter(i=>i.id!==item.id)})}>{adminText("Remove")}</button></div><div className="adm-grid-2"><label className="adm-field">{adminText("Stage name (EN)")}<input required value={item.nameEn} onChange={e=>editStage(item.id,{nameEn:e.target.value})}/></label><label className="adm-field">{adminText("Stage name (AR)")}<input dir="rtl" value={item.nameAr||''} onChange={e=>editStage(item.id,{nameAr:e.target.value})}/></label><label className="adm-field">{adminText("Responsible department")}<select value={item.responsibleDepartmentId||''} onChange={e=>editStage(item.id,{responsibleDepartmentId:e.target.value||null})}><option value="">{adminText("Assign on project")}</option>{departments.map(d=><option key={d.id} value={d.id}>{d.nameEn}</option>)}</select></label><label className="adm-field">{adminText("Responsible role")}<input value={item.responsibleRole||''} placeholder={adminText("e.g. Lead architect")} onChange={e=>editStage(item.id,{responsibleRole:e.target.value})}/></label></div><label className="adm-field">{adminText("Required deliverables")}<input value={item.requiredDocuments||''} placeholder={adminText("e.g. Design drawings, calculation report")} onChange={e=>editStage(item.id,{requiredDocuments:e.target.value})}/></label><label className="adm-check"><input type="checkbox" checked={item.requiresApproval||false} onChange={e=>editStage(item.id,{requiresApproval:e.target.checked})}/>{adminText("Approval required before completion")}</label></div>)}
    {canWrite&&<button className="adm-btn-ghost" type="button" onClick={()=>setDraft({...draft,items:[...draft.items,newStage()]})}>{adminText("+ Add stage")}</button>}</fieldset></div>{canWrite&&<div className="adm-modal-foot"><button className="adm-btn" disabled={saving}>{adminText(saving?'Saving…':'Save workflow')}</button></div>}</form></div></div>}
  </div>;
}
