'use client';
import {adminText} from '@/lib/admin/translate';

import {useState} from 'react';
import AdminCloseButton from '@/components/admin/ui/AdminCloseButton';
export default function TaskQuickCreate({projects,employees,onClose,onSaved}) {
  const [draft,setDraft]=useState({title:'',projectId:'',assigneeIds:[],priority:'normal',dueDate:'',estimatedHours:'',description:''});
  const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  async function save(e){e.preventDefault();setSaving(true);setError('');try{const res=await fetch('/api/admin/ops',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'tasks',document:draft})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not create task');await onSaved();onClose();}catch(err){setError(err.message);}finally{setSaving(false);}}
  return <div className="adm-modal-backdrop" onClick={()=>!saving&&onClose()}><div className="adm-modal" role="dialog" aria-modal="true" aria-label={adminText("Create task")} onClick={e=>e.stopPropagation()}><div className="adm-modal-head"><h2>{adminText("New task")}</h2><AdminCloseButton disabled={saving} onClick={onClose}/></div><form onSubmit={save}><div className="adm-modal-body">{error&&<p className="adm-error" role="alert">{adminText(error)}</p>}<fieldset disabled={saving} style={{border:0,padding:0}}><label className="adm-field">{adminText("Task title")}<input required autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="adm-grid-2"><label className="adm-field">{adminText("Project")}<select required value={draft.projectId} onChange={e=>setDraft({...draft,projectId:e.target.value})}><option value="">{adminText("Select project")}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.nameEn}</option>)}</select></label><label className="adm-field">{adminText("Owner")}<select value={draft.assigneeIds[0]||''} onChange={e=>setDraft({...draft,assigneeIds:e.target.value?[e.target.value]:[]})}><option value="">{adminText("Unassigned")}</option>{employees.map(p=><option key={p.id} value={p.id}>{p.fullNameEn}</option>)}</select></label><label className="adm-field">{adminText("Due date")}<input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label className="adm-field">{adminText("Priority")}<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{['low','normal','high','urgent'].map(p=><option key={p} value={p}>{adminText(p)}</option>)}</select></label><label className="adm-field">{adminText("Estimated effort (hours)")}<input type="number" min="0" step="0.5" value={draft.estimatedHours} onChange={e=>setDraft({...draft,estimatedHours:e.target.value})}/></label></div><label className="adm-field">{adminText("Description")}<textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></fieldset></div><div className="adm-modal-foot"><button className="adm-btn" disabled={saving}>{adminText(saving?'Creating…':'Create task')}</button></div></form></div></div>;
}
