/**
 * Temporary demo TeamMember payloads for UI preview.
 * Seeded into the file-backed store — editable/deletable from /admin/team.
 */

export const DEMO_TEAM_MEMBERS = [
  {
    slug: 'ahmad-al-faisal',
    name_en: 'Ahmad Al Faisal',
    name_ar: 'أحمد الفيصل',
    job_title_en: 'Managing Director',
    job_title_ar: 'المدير العام',
    department_id: 'leadership',
    department_en: 'Leadership',
    department_ar: 'القيادة',
    short_bio_en:
      'Leads ASAS with a focus on coordinated engineering delivery, client clarity and disciplined project outcomes across Abu Dhabi.',
    short_bio_ar:
      'يقود أساس للاستشارات الهندسية وإدارة المشاريع مع التركيز على التسليم الهندسي المنسق ووضوح متطلبات العملاء ونتائج المشاريع المنضبطة عبر أبوظبي.',
    full_bio_en:
      'Ahmad Al Faisal guides the strategic direction of ASAS Engineering & Project Management Consultancy. He works closely with discipline leads to keep architectural, structural and electromechanical work aligned from concept through construction support.\n\nHis priorities include clear client communication, coordinated design packages and reliable delivery standards that support both private and institutional projects in the UAE.',
    full_bio_ar:
      'يوجّه أحمد الفيصل التوجه الاستراتيجي لمكتب أساس للاستشارات الهندسية وإدارة المشاريع. ويعمل عن قرب مع قادة التخصصات للحفاظ على انسجام الأعمال المعمارية والإنشائية والكهروميكانيكية من الفكرة حتى دعم التنفيذ.\n\nوتشمل أولوياته التواصل الواضح مع العملاء وحزم التصميم المنسقة ومعايير التسليم الموثوقة التي تدعم المشاريع الخاصة والمؤسسية في دولة الإمارات.',
    profile_image: '',
    years_experience: '20+',
    expertise_en: ['Strategic Leadership', 'Engineering Consultancy', 'Project Delivery', 'Client Relations'],
    expertise_ar: ['القيادة الاستراتيجية', 'الاستشارات الهندسية', 'تسليم المشاريع', 'علاقات العملاء'],
    education_en: ['BSc Civil Engineering'],
    education_ar: ['بكالوريوس الهندسة المدنية'],
    qualifications_en: ['Engineering management and consultancy leadership'],
    qualifications_ar: ['قيادة الإدارة والاستشارات الهندسية'],
    quote_en: 'Good engineering starts with understanding the problem clearly.',
    quote_ar: 'تبدأ الهندسة الجيدة بفهم المشكلة بوضوح.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['four-towers-al-nahda', 'mbz-city-towers'],
    featured: true,
    leadership: true,
    display_order: 1,
    status: 'published',
    seo_title_en: 'Ahmad Al Faisal | Managing Director | ASAS',
    seo_title_ar: 'أحمد الفيصل | المدير العام | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'Managing Director at ASAS Engineering & Project Management Consultancy, Abu Dhabi.',
    seo_description_ar: 'المدير العام في أساس للاستشارات الهندسية وإدارة المشاريع، أبوظبي.',
  },
  {
    slug: 'asaad-moghrabi',
    name_en: 'Asaad Moghrabi',
    name_ar: 'أسعد المغربي',
    job_title_en: 'Director of Engineering',
    job_title_ar: 'مدير الهندسة',
    department_id: 'leadership',
    department_en: 'Engineering',
    department_ar: 'الهندسة',
    short_bio_en:
      'Oversees multidisciplinary engineering coordination across architecture, structure and MEP for ASAS project packages.',
    short_bio_ar:
      'يشرف على تنسيق الهندسة متعددة التخصصات عبر العمارة والإنشاءات وMEP لحزم مشاريع أساس للاستشارات الهندسية وإدارة المشاريع.',
    full_bio_en:
      'Asaad Moghrabi leads engineering coordination at ASAS, ensuring design decisions remain coherent across disciplines. He supports technical reviews, interface checking and delivery readiness for complex building and planning assignments.\n\nHis work emphasizes practical constructability, clear documentation and close collaboration between design teams and project management.',
    full_bio_ar:
      'يقود أسعد المغربي تنسيق الهندسة في أساس للاستشارات الهندسية وإدارة المشاريع لضمان بقاء قرارات التصميم متسقة عبر التخصصات. ويدعم المراجعات الفنية وفحص الواجهات وجاهزية التسليم للمهام المعقدة في المباني والتخطيط.\n\nويركز عمله على قابلية التنفيذ العملية والتوثيق الواضح والتعاون الوثيق بين فرق التصميم وإدارة المشاريع.',
    profile_image: '',
    years_experience: '18+',
    expertise_en: [
      'Multidisciplinary Coordination',
      'Architectural Engineering',
      'Structural Engineering',
      'MEP Coordination',
    ],
    expertise_ar: ['التنسيق متعدد التخصصات', 'الهندسة المعمارية', 'الهندسة الإنشائية', 'تنسيق MEP'],
    education_en: ['BSc Architectural Engineering'],
    education_ar: ['بكالوريوس الهندسة المعمارية'],
    qualifications_en: ['Cross-discipline design coordination'],
    qualifications_ar: ['تنسيق التصميم بين التخصصات'],
    quote_en: 'Coordination is where engineering intent becomes buildable.',
    quote_ar: 'التنسيق هو ما يجعل النية الهندسية قابلة للتنفيذ.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['culture-private-school', 'compound-villas-portfolio'],
    featured: true,
    leadership: true,
    display_order: 2,
    status: 'published',
    seo_title_en: 'Asaad Moghrabi | Director of Engineering | ASAS',
    seo_title_ar: 'أسعد المغربي | مدير الهندسة | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'Director of Engineering at ASAS, focused on multidisciplinary project coordination.',
    seo_description_ar: 'مدير الهندسة في أساس للاستشارات الهندسية وإدارة المشاريع، متخصص في تنسيق المشاريع متعددة التخصصات.',
  },
  {
    slug: 'mufaq-abdelbaset',
    name_en: 'Mufaq Abdelbaset',
    name_ar: 'موفق عبد الباسط',
    job_title_en: 'Senior Structural Engineer',
    job_title_ar: 'مهندس إنشائي أول',
    department_id: 'structural',
    department_en: 'Structural Engineering',
    department_ar: 'الهندسة الإنشائية',
    short_bio_en:
      'Delivers structural design and technical review for mid- and high-rise buildings with a focus on clarity and buildability.',
    short_bio_ar:
      'يقدم التصميم الإنشائي والمراجعة الفنية للمباني المتوسطة والعالية مع التركيز على الوضوح وقابلية التنفيذ.',
    full_bio_en:
      'Mufaq Abdelbaset contributes structural analysis, detailing and review for ASAS building projects. He works with architecture and MEP teams to resolve load paths, framing strategies and construction interfaces early.\n\nHis approach balances code compliance, material efficiency and practical site conditions across residential, commercial and mixed-use work.',
    full_bio_ar:
      'يساهم موفق عبد الباسط في التحليل الإنشائي والتفصيل والمراجعة لمشاريع مباني أساس للاستشارات الهندسية وإدارة المشاريع. ويعمل مع فرق العمارة وMEP لمعالجة مسارات الأحمال واستراتيجيات الإطارات وواجهات التنفيذ مبكراً.\n\nويوازن نهجه بين الالتزام بالكود وكفاءة المواد وظروف الموقع العملية عبر الأعمال السكنية والتجارية والاستخدام المختلط.',
    profile_image: '',
    years_experience: '14+',
    expertise_en: ['Structural Design', 'Reinforced Concrete', 'High-Rise Buildings', 'Technical Review'],
    expertise_ar: ['التصميم الإنشائي', 'الخرسانة المسلحة', 'المباني العالية', 'المراجعة الفنية'],
    education_en: ['BSc Civil / Structural Engineering'],
    education_ar: ['بكالوريوس الهندسة المدنية / الإنشائية'],
    qualifications_en: ['Structural design and documentation'],
    qualifications_ar: ['التصميم الإنشائي والتوثيق'],
    quote_en: 'Structure should support the architecture, not fight it.',
    quote_ar: 'ينبغي أن يدعم الإنشاء العمارة لا أن يتعارض معها.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['four-towers-al-nahda', 'residential-building-al-raha-rbw2'],
    featured: true,
    leadership: false,
    display_order: 3,
    status: 'published',
    seo_title_en: 'Mufaq Abdelbaset | Senior Structural Engineer | ASAS',
    seo_title_ar: 'موفق عبد الباسط | مهندس إنشائي أول | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'Senior Structural Engineer at ASAS for building and high-rise structural design.',
    seo_description_ar: 'مهندس إنشائي أول في أساس للاستشارات الهندسية وإدارة المشاريع لتصميم المباني والأبراج.',
  },
  {
    slug: 'mohammed-sami',
    name_en: 'Mohammed Sami',
    name_ar: 'محمد سامي',
    job_title_en: 'MEP Engineering Manager',
    job_title_ar: 'مدير الهندسة الكهروميكانيكية',
    department_id: 'mep',
    department_en: 'MEP',
    department_ar: 'الكهروميكانيكية',
    short_bio_en:
      'Manages electromechanical design coordination for efficient, maintainable building systems across ASAS projects.',
    short_bio_ar:
      'يدير تنسيق التصميم الكهروميكانيكي لأنظمة المباني الكفؤة والقابلة للصيانة عبر مشاريع أساس للاستشارات الهندسية وإدارة المشاريع.',
    full_bio_en:
      'Mohammed Sami leads MEP engineering coordination at ASAS, covering mechanical, electrical and plumbing design interfaces. He works with architecture and structure to keep service routes, plant space and performance requirements aligned.\n\nHis focus includes energy-conscious system choices, clear drawings and practical supervision support during delivery.',
    full_bio_ar:
      'يقود محمد سامي تنسيق هندسة MEP في أساس للاستشارات الهندسية وإدارة المشاريع، ويغطي واجهات التصميم الميكانيكي والكهربائي والصحي. ويعمل مع العمارة والإنشاءات للحفاظ على توافق مسارات الخدمات ومساحات المعدات ومتطلبات الأداء.\n\nويركز على اختيارات الأنظمة الواعية بالطاقة والرسومات الواضحة ودعم الإشراف العملي أثناء التسليم.',
    profile_image: '',
    years_experience: '15+',
    expertise_en: ['Mechanical Engineering', 'Electrical Engineering', 'Plumbing Systems', 'MEP Coordination'],
    expertise_ar: ['الهندسة الميكانيكية', 'الهندسة الكهربائية', 'أنظمة الأعمال الصحية', 'تنسيق MEP'],
    education_en: ['BSc Mechanical / Electromechanical Engineering'],
    education_ar: ['بكالوريوس الهندسة الميكانيكية / الكهروميكانيكية'],
    qualifications_en: ['MEP design management'],
    qualifications_ar: ['إدارة تصميم MEP'],
    quote_en: 'Services succeed when coordination happens before construction.',
    quote_ar: 'تنجح الخدمات عندما يتم التنسيق قبل التنفيذ.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['building-mbz-musaffah-m26', 'industrial-facility-musaffah-m42'],
    featured: true,
    leadership: false,
    display_order: 4,
    status: 'published',
    seo_title_en: 'Mohammed Sami | MEP Engineering Manager | ASAS',
    seo_title_ar: 'محمد سامي | مدير الهندسة الكهروميكانيكية | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'MEP Engineering Manager at ASAS coordinating mechanical, electrical and plumbing design.',
    seo_description_ar: 'مدير الهندسة الكهروميكانيكية في أساس للاستشارات الهندسية وإدارة المشاريع لتنسيق التصميم الميكانيكي والكهربائي والصحي.',
  },
  {
    slug: 'omar-hassan',
    name_en: 'Omar Hassan',
    name_ar: 'عمر حسن',
    job_title_en: 'Senior Architect',
    job_title_ar: 'مهندس معماري أول',
    department_id: 'architecture',
    department_en: 'Architecture',
    department_ar: 'العمارة',
    short_bio_en:
      'Develops architectural concepts and coordinated documentation for residential, commercial and educational projects.',
    short_bio_ar:
      'يطور المفاهيم المعمارية والتوثيق المنسق للمشاريع السكنية والتجارية والتعليمية.',
    full_bio_en:
      'Omar Hassan works across concept development, design development and technical documentation at ASAS. He collaborates with structure and MEP to keep spatial intent, code requirements and construction detail aligned.\n\nHis portfolio interest spans villas, compounds, schools and mixed-use buildings where clear architectural narrative and coordinated drawings matter.',
    full_bio_ar:
      'يعمل عمر حسن عبر تطوير الفكرة وتطوير التصميم والتوثيق الفني في أساس للاستشارات الهندسية وإدارة المشاريع. ويتعاون مع الإنشاءات وMEP للحفاظ على توافق النية الفراغية ومتطلبات الكود وتفاصيل التنفيذ.\n\nوتمتد اهتماماته عبر الفلل والمجمعات والمدارس والمباني متعددة الاستخدام حيث تهم السردية المعمارية الواضحة والرسومات المنسقة.',
    profile_image: '',
    years_experience: '12+',
    expertise_en: ['Architectural Design', 'Concept Development', 'Design Coordination', 'Technical Documentation'],
    expertise_ar: ['التصميم المعماري', 'تطوير الفكرة', 'تنسيق التصميم', 'التوثيق الفني'],
    education_en: ['BArch / BSc Architecture'],
    education_ar: ['بكالوريوس العمارة'],
    qualifications_en: ['Architectural design and documentation'],
    qualifications_ar: ['التصميم المعماري والتوثيق'],
    quote_en: 'Architecture holds the project together when coordination is built in.',
    quote_ar: 'تحافظ العمارة على تماسك المشروع عندما يُبنى التنسيق ضمنها.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['compound-villas-portfolio', 'private-villa-shakhbout-w01'],
    featured: true,
    leadership: false,
    display_order: 5,
    status: 'published',
    seo_title_en: 'Omar Hassan | Senior Architect | ASAS',
    seo_title_ar: 'عمر حسن | مهندس معماري أول | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'Senior Architect at ASAS focused on concept development and coordinated documentation.',
    seo_description_ar: 'مهندس معماري أول في أساس للاستشارات الهندسية وإدارة المشاريع يركز على تطوير الفكرة والتوثيق المنسق.',
  },
  {
    slug: 'sara-khaled',
    name_en: 'Sara Khaled',
    name_ar: 'سارة خالد',
    job_title_en: 'Project Management Specialist',
    job_title_ar: 'أخصائية إدارة مشاريع',
    department_id: 'project-management',
    department_en: 'Project Management',
    department_ar: 'إدارة المشاريع',
    short_bio_en:
      'Supports project planning, tender coordination and delivery monitoring across ASAS consultancy assignments.',
    short_bio_ar:
      'تدعم تخطيط المشاريع وتنسيق العطاءات ومتابعة التسليم عبر مهام استشارات أساس للاستشارات الهندسية وإدارة المشاريع.',
    full_bio_en:
      'Sara Khaled connects design progress with project controls at ASAS. She supports scheduling, coordination meetings, tender documentation and communication between clients, designers and site teams.\n\nHer work helps keep deliverables on track from design through construction support and handover readiness.',
    full_bio_ar:
      'تربط سارة خالد تقدم التصميم مع ضوابط المشروع في أساس للاستشارات الهندسية وإدارة المشاريع. وتدعم الجدولة واجتماعات التنسيق ووثائق العطاء والتواصل بين العملاء والمصممين وفرق الموقع.\n\nويساعد عملها في الحفاظ على المسار الصحيح للمخرجات من التصميم حتى دعم التنفيذ وجاهزية التسليم.',
    profile_image: '',
    years_experience: '10+',
    expertise_en: ['Project Planning', 'Coordination', 'Tender Management', 'Construction Monitoring'],
    expertise_ar: ['تخطيط المشاريع', 'التنسيق', 'إدارة العطاءات', 'متابعة التنفيذ'],
    education_en: ['BSc Project Management / Engineering'],
    education_ar: ['بكالوريوس إدارة المشاريع / الهندسة'],
    qualifications_en: ['Project coordination and tender support'],
    qualifications_ar: ['تنسيق المشاريع ودعم العطاءات'],
    quote_en: 'Clear planning keeps engineering teams aligned through delivery.',
    quote_ar: 'التخطيط الواضح يحافظ على انسجام الفرق الهندسية خلال التسليم.',
    linkedin_url: 'https://www.linkedin.com/',
    notable_projects: ['traffic-access-studies', 'culture-private-school'],
    featured: true,
    leadership: false,
    display_order: 6,
    status: 'published',
    seo_title_en: 'Sara Khaled | Project Management Specialist | ASAS',
    seo_title_ar: 'سارة خالد | أخصائية إدارة مشاريع | أساس للاستشارات الهندسية وإدارة المشاريع',
    seo_description_en: 'Project Management Specialist at ASAS supporting planning, tender and delivery coordination.',
    seo_description_ar: 'أخصائية إدارة مشاريع في أساس للاستشارات الهندسية وإدارة المشاريع لدعم التخطيط والعطاء وتنسيق التسليم.',
  },
];
