import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.cwd();const temp=await mkdtemp(path.join(tmpdir(),'asas-erp-tests-'));
process.env.ASAS_ERP_DB=path.join(temp,'erp.sqlite');
let passed=0;
try{
  await mkdir(path.join(temp,'.data','ops'),{recursive:true});
  for(const [name,items] of Object.entries({clients:[{id:'c1',nameEn:'QA Client'}],projects:[{id:'p1',nameEn:'QA Project',code:'QA1',clientId:'c1'}],employees:[{id:'e1',fullNameEn:'QA Employee'},{id:'e2',fullNameEn:'Second Employee'}]}))await writeFile(path.join(temp,'.data','ops',`${name}.json`),JSON.stringify(items));
  process.chdir(temp);
  const engine=await import(pathToFileURL(path.join(root,'lib/erp/engine.js')));const dbmod=await import(pathToFileURL(path.join(root,'lib/erp/database.js')));const reports=await import(pathToFileURL(path.join(root,'lib/erp/reports.js')));const {documentTotals,fixed}=await import(pathToFileURL(path.join(root,'lib/erp/money.js')));
  const admin={id:'qa-admin',role:'super_admin',permissions:[]};const clerk={id:'clerk',role:'finance_clerk',permissions:['erp.finance.read','erp.finance.write']};const reviewer={id:'reviewer',role:'finance_manager',permissions:['erp.finance.read','erp.finance.write','erp.finance.approve','erp.finance.post']};
  const check=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
  const save=(module,data,actor=admin)=>engine.saveDocument(module,data,actor);
  const act=(doc,action,extras={},actor=admin)=>engine.actOnDocument(doc.module,doc.id,action,{version:doc.version,...extras},actor);
  const line=(price=100,tax=5)=>[{description:'Engineering design',quantity:1,unitPrice:price,taxRate:tax}];
  const invoiceInput={title:'Design invoice',clientId:'c1',projectId:'p1',date:'2026-09-01',dueDate:'2026-09-30',lines:line()};
  await check('integer money calculations round each tax line',()=>assert.deepEqual(documentTotals([{description:'Fraction',quantity:3,unitPrice:'0.10',taxRate:5}]).totalMinor,32));
  await check('decimal rounding avoids binary floating point loss',()=>assert.equal(fixed('1.005'),101));
  await check('retrying a create request cannot duplicate a document',()=>{const input={...invoiceInput,requestId:'retry-test'};const first=save('invoices',input);assert.equal(save('invoices',input).id,first.id);assert.throws(()=>save('invoices',{...input,title:'Changed'}),/different data/);assert.throws(()=>save('quotations',input),/different data/);});
  await check('negative and invalid financial amounts rejected',()=>assert.throws(()=>documentTotals(line(-1)),/non-negative/));
  await check('unauthorized readers cannot access payroll',()=>assert.throws(()=>engine.listDocuments('payroll',clerk),/permission/));
  await check('invalid project references rejected',()=>assert.throws(()=>save('invoices',{...invoiceInput,projectId:'bad'}),/no longer exists/));
  let invoice=save('invoices',invoiceInput,clerk);
  await check('untrusted totals and status are ignored',()=>{const r=save('invoices',{...invoiceInput,title:'Computed',totalMinor:1,status:'posted'});assert.equal(r.totalMinor,10500);assert.equal(r.status,'draft');});
  await check('stale updates are rejected',()=>assert.throws(()=>save('invoices',{...invoice,version:0}),/changed/));
  await check('clerks cannot post invoices',()=>assert.throws(()=>act(invoice,'post',{},clerk),/permission/));
  invoice=act(invoice,'post',{},reviewer);
  await check('posting creates balanced ledger lines',()=>{const rows=dbmod.database().prepare('SELECT debit,credit FROM ledger_lines WHERE entry_id=?').all(invoice.ledgerId);assert.equal(rows.reduce((n,r)=>n+r.debit-r.credit,0),0);assert.equal(rows.reduce((n,r)=>n+r.debit,0),10500);});
  await check('posted invoices cannot be edited',()=>assert.throws(()=>save('invoices',{...invoice,title:'Tampered'}),/draft/));
  await check('double posting rejected without extra ledger rows',()=>{const count=dbmod.database().prepare('SELECT COUNT(*) n FROM ledger').get().n;assert.throws(()=>act(invoice,'post'),/not available/);assert.equal(dbmod.database().prepare('SELECT COUNT(*) n FROM ledger').get().n,count);});
  let pay=save('payments',{title:'Partial receipt',date:'2026-09-03',target:invoice.id,amount:40,bankAccount:'1000',reference:'BANK-001'});pay=act(pay,'post');
  await check('partial receipt reduces receivables',()=>assert.equal(engine.listDocuments('invoices',admin).find(r=>r.id===invoice.id).outstandingMinor,6500));
  await check('overpayments rejected',()=>assert.throws(()=>save('payments',{title:'Too much',date:'2026-09-03',target:invoice.id,amount:70,bankAccount:'1000',reference:'BANK-002'}),/exceeds/));
  let statement=save('reconciliation',{title:'Bank statement',date:'2026-09-03',bankAccount:'1000',direction:'receipt',amount:40,reference:'ST-001',paymentId:pay.id});statement=act(statement,'match');
  await check('reconciled payments cannot be reversed',()=>assert.throws(()=>act(pay,'reverse',{date:'2026-09-04',reason:'Correction'}),/Unmatch/));
  statement=act(statement,'unmatch');pay=act(pay,'reverse',{date:'2026-09-04',reason:'Correction'});
  await check('payment reversal restores receivable balance',()=>assert.equal(engine.listDocuments('invoices',admin).find(r=>r.id===invoice.id).outstandingMinor,10500));
  await check('historical receivables include payments before their reversal date',()=>assert.equal(reports.financialReports(admin,'2026-09-01','2026-09-03').aging.find(r=>r.id===invoice.id).outstanding,6500));
  invoice=act(invoice,'reverse',{date:'2026-09-05',reason:'Cancelled scope'});
  await check('invoice reversal retains original and offsets ledger',()=>{const report=reports.financialReports(admin,'2026-09-01','2026-09-30');assert.equal(report.income,0);assert.equal(report.trial.find(a=>a.code==='1100').balance,0);});
  const vendor=save('vendors',{name:'QA Supplier',email:'qa@example.test'});
  let po=save('purchase-orders',{title:'Survey services',date:'2026-09-01',vendorId:vendor.id,projectId:'p1',lines:line(200,0)});po=act(po,'submit');po=act(po,'approve');po=act(po,'receive');po=act(po,'bill');
  await check('purchase conversion creates one traceable draft bill',()=>{const bill=dbmod.getRecord(po.convertedId);assert.equal(bill.module,'bills');assert.equal(bill.sourceId,po.id);assert.equal(bill.status,'draft');assert.throws(()=>act(po,'bill'),/not available/);});
  let bill=dbmod.getRecord(po.convertedId);bill=save('bills',{...bill,reference:'SUP-001'});bill=act(bill,'post');
  await check('supplier reference prevents duplicate bills',()=>assert.throws(()=>save('bills',{...bill,id:undefined,version:undefined}),/already recorded/));
  await check('supplier posting reaches payables and project costs',()=>{const report=reports.financialReports(admin,'2026-09-01','2026-09-30');assert.equal(report.trial.find(a=>a.code==='2000').balance,-20000);assert.equal(report.projects[0].ledgerCost,20000);});
  let quotation=save('quotations',{...invoiceInput,title:'Proposal'});quotation=act(quotation,'submit');quotation=act(quotation,'approve');quotation=act(quotation,'contract');let contract=dbmod.getRecord(quotation.convertedId);contract=act(contract,'submit');contract=act(contract,'approve');contract=act(contract,'invoice');
  await check('sales cycle links proposal contract and invoice',()=>assert.equal(dbmod.getRecord(contract.convertedId).sourceId,contract.id));
  let expense=save('expenses',{title:'Travel',date:'2026-09-02',employeeId:'e1',projectId:'p1',amount:50,receiptReference:'R-01'},clerk);expense=act(expense,'submit',{},clerk);
  await check('maker cannot approve own expense without administrator override',()=>assert.throws(()=>act(expense,'approve',{}, {...clerk,permissions:[...clerk.permissions,'erp.finance.approve']}),/different/));
  expense=act(expense,'approve',{},reviewer);expense=act(expense,'post',{},reviewer);
  let payroll=save('payroll',{title:'September payroll',date:'2026-09-25',period:'2026-09',employees:[{employeeId:'e1',base:1000,allowance:100,deduction:50}]});
  await check('payroll net is calculated on server',()=>assert.equal(payroll.totalMinor,105000));
  await check('duplicate employee payroll periods rejected',()=>assert.throws(()=>save('payroll',{...payroll,id:undefined,version:undefined}),/already has payroll/));
  payroll=act(payroll,'submit');payroll=act(payroll,'approve');payroll=act(payroll,'post');
  await check('payroll posts gross expense, net pay and withholdings',()=>{const trial=reports.financialReports(admin,'2026-09-01','2026-09-30').trial;assert.equal(trial.find(a=>a.code==='2300').balance,-105000);assert.equal(trial.find(a=>a.code==='5200').balance,110000);assert.equal(trial.find(a=>a.code==='2400').balance,-5000);});
  await check('payroll settlement cannot be created by staff without HR access',()=>assert.throws(()=>save('payments',{title:'Payroll payment',date:'2026-09-25',target:payroll.id,amount:1050,bankAccount:'1000',reference:'SAL-01'},clerk),/Payroll access/));
  let time=save('time-entries',{title:'Design coordination',date:'2026-09-01',employeeId:'e1',projectId:'p1',hours:8,hourlyCost:100,billable:true});time=act(time,'submit');time=act(time,'approve');
  await check('daily employee hours cannot exceed 24',()=>assert.throws(()=>save('time-entries',{...time,id:undefined,version:undefined,hours:20}),/exceed 24/));
  await check('approved time is management cost without ledger duplication',()=>assert.equal(reports.financialReports(admin,'2026-09-01','2026-09-30').projects[0].effortCost,80000));
  let asset=save('assets',{title:'Workstation',date:'2026-09-01',vendorId:vendor.id,amount:1200,salvageValue:0,lifeMonths:12,serialNumber:'ASSET-1'});asset=act(asset,'post');asset=act(asset,'depreciate',{date:'2026-09-30'});
  await check('straight line depreciation posts a monthly balanced expense',()=>assert.equal(asset.depreciatedMinor,10000));
  await check('same monthly depreciation cannot be posted twice',()=>assert.throws(()=>act(asset,'depreciate',{date:'2026-09-30'}),/already posted/));
  await check('unbalanced manual journals rejected',()=>assert.throws(()=>save('journals',{title:'Bad journal',date:'2026-09-01',lines:[{account:'1000',debit:100,credit:0},{account:'3000',debit:0,credit:99}]}),/balance/));
  let opening=save('journals',{title:'Opening funds',date:'2026-09-01',lines:[{account:'1000',debit:10000,credit:0},{account:'3000',debit:0,credit:10000}]});opening=act(opening,'post');
  await check('balance sheet balances after complete business cycles',()=>{const r=reports.financialReports(admin,'2026-09-01','2026-09-30');assert.equal(r.balanceSheet.assets,r.balanceSheet.liabilities+r.balanceSheet.equity+r.balanceSheet.retained);assert.equal(r.trial.reduce((n,a)=>n+a.debit-a.credit,0),0);});
  let delayed=save('invoices',{...invoiceInput,title:'Closed period draft'});
  engine.updateSettings({...engine.companySettings(admin),closedThrough:'2026-09-30'},admin);
  await check('closed periods block posting with complete rollback',()=>{const before=dbmod.database().prepare('SELECT COUNT(*) n FROM ledger').get().n;assert.throws(()=>act(delayed,'post'),/closed/);assert.equal(dbmod.getRecord(delayed.id).status,'draft');assert.equal(dbmod.database().prepare('SELECT COUNT(*) n FROM ledger').get().n,before);});
  await check('company currency cannot change after documents exist',()=>assert.throws(()=>engine.updateSettings({...engine.companySettings(admin),currency:'USD'},admin),/cannot change/));
  await check('audit is written for business mutations',()=>assert.ok(engine.auditTrail(admin).some(r=>r.action==='post')));
  await check('database integrity and foreign keys are valid',()=>{assert.equal(dbmod.database().prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(dbmod.database().prepare('PRAGMA foreign_key_check').all().length,0);});
  console.log(`${passed} ERP checks passed using isolated synthetic company data.`);
  dbmod.database().close();
}finally{process.chdir(root);await rm(temp,{recursive:true,force:true});delete process.env.ASAS_ERP_DB;}
